### ISSUE TITLE
Leaflet map has wrong initial center and scale on Firefox

### ISSUE THREAD

**Issue by sashahart** [TNRIS/flood#108]
When running master (e.g. 207b6e790c5b34d73ab71bb97001f8cca12d700e) locally via `npm start`, it seems that the slippy map's bounds are somehow not getting set correctly because on page load, we see only about the lower half of Texas all the way at the top of the screen, with the map zoomed out probably more than we want for a map of Texas. (edit: to be very clear, only on Firefox; things work as expected even for the local app on Chrome.)

I believe Chris noticed the same or a related issue when running the app the same way and viewing it via Firefox.

Certain events (like resizing the development console pane) may trigger a correct recentering, but not affect the wrong zoom level.

I couldn't say whether master will function as expected on deployment, but I would be concerned about whether deploying master will result in this malfunction for Firefox users, if it does not look correct in Firefox when run locally.

Just to be clear, the actual production app at http://map.texasflood.org/ is working correctly on Firefox right now, but I'm not sure which git revision that deploy was.

**Comment by wilsaj** [comment]
Just did some testing and this doesn't appear to be affecting production builds, as tested by:
```
npm run dist
cd dist/
python -m SimpleHTTPServer
```

With production builds, all of the css is minified and split into a separate file and included via `<style>` tag, but with webpack's dev server the css assets are bundled and served *as javascript* so that CSS can be hot loaded (and styles can changed on-the-fly without requiring a full hard refresh of the app).

This would explain the behavior with the race condition and why we don't see this bug in production.

**Comment by sashahart** [comment]
Then the readme should specifically discourage using `npm start` and provide some alternative spec for setting up a test environment where we can verify that build behavior is as intended.

We also need deploys to use a version tag that is documented somewhere as the currently deployed version.

Otherwise it is not easy to determine if observed bugs are due to build mysteries or differences between deploy and master, or if the app is indeed just broken on Firefox.
