### ISSUE TITLE
bad encoding of quotes within legal disclaimer

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#110]
as seen on Safari, Chrome and Firefox on OSX:

<img width="462" alt="screen shot 2016-06-22 at 5 03 10 pm" src="https://cloud.githubusercontent.com/assets/303866/16285389/735127e4-389b-11e6-88be-e13bb7283268.png">

**Comment by sashahart** [comment]
I'm not seeing it locally in any browser, so it could be a matter of what encoding is being served from the web server. Tedious.

A quick fix would be to use "dumb" quotes. I think it would look good enough. I think I'll PR that in the next few minutes.

The only reason this even has "smart quotes" to begin with is that I used verbatim the text I was given, which probably had smart quotes because it was pasted from Word or something.

**Comment by sashahart** [comment]
Looks good on the live site, thanks Andy!
