### ISSUE TITLE
Weather Alerts - Aeris has tile layers for severe weather alerts

### ISSUE THREAD

**Issue by jseppi** [TNRIS/flood#25]
A map layer containing active Watches and Warnings from the National Weather Service
## source
- available through Aeris weather, which updates every 2-3 minutes. See the "Severe" tab on http://www.aerisweather.com/support/docs/aeris-maps/reference/map-layers/
- There is even a layer just for "Alerts (Flood Related)"
- original source of data is NWS: http://www.weather.gov/ 
- have a rough pass at a five-minute updating geojson layer at http://labs.tnris.org/alerts.geojson
## status
- [ ] waiting on procurement of Aeris subscription #31

**Comment by jseppi** [comment]
Legends assets are available: http://www.aerisweather.com/support/docs/aeris-maps/reference/legends/

**Comment by jseppi** [comment]
There doesn't appear to be UTFGrid support, but there are many Aeris data endpoints that can be queried. Each one would have to be a bit customized, but the API is documented well: http://www.aerisweather.com/support/docs/api/reference/endpoints/advisories/

**Comment by wilsaj** [comment]
That looks great - updates every 2-3 minutes. I think info on click should be fine, trying to roll our own layer with that small of a refresh window would be tricky.

**Comment by wilsaj** [comment]
merged in 7773373

As noted in the PR, the Aeris alerts and advisories service has some shortcomings which make this less than :100: :
- doesn't currently allow a way to definitively request info for advisories at a given point - this is how point + radius queries should work in theory but they miss pretty often, esp. with arbitrary polygons (not county-wide) and that's what flood warnings often are :(
- because of this, we have to default to showing more flood info than we care to - sometimes when you click near an alert poly but not quite on one, you still get a popup
- had to hack around the fact that it returns duplicate warning info sometimes. If an alert is issues for multiple counties, we get multiple copies of it. kinda dumb.
- does not include the warning ID, so we have no way of linking back to the official NWS site for the warning
- the 'flood' subset doesn't do a good job of representing all the things we want to show - it doesn't include sever storm warnings, for example, nor does it include coastal floods. So we're just using the "every possible alert" layer / service for now

We should follow up with Aeris and ask them what's up / point out the issues when we have some spare time.

If this is considered too broken, we could resort to rendering and updating our own layer but that's going to take some effort.

**Comment by wilsaj** [comment]
...also, I'm sometimes finding alert polygons that are just not returning anything from the service 😞
