### ISSUE TITLE
Data Pipeline and Service Architecture

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#36]
This issue is to track high level data pipeline and service architecture discussion

## data pipeline needs
- data will be collected from different sources (such as NWS, USGS, Texas Mesonet, MesoWest, and *many more*)
- pipeline needs to take data through Extract, Transform, Load (ETL) and allow for additional processing steps
- will load data into some persistent, queryable data store (probably either DynamoDB or postgresql hosted via RDS)
- **modular**: 
    - each data source works differently, so our pipeline should accommodate that
      - have its own ETL process and schedule as appropriate
      - ideally we would be able to use any script, CLI tool, etc so that we don't need to reinvent any wheels
    - we should try to keep it simple as possible so we can plug in new people and distribute workload
- **fault-tolerant**:
  - if a service is unavailable for any reason, then retry after a short timeout
  - if a service is down for a while, email notifications should be sent to us (small number of people) to take a look at it
  - always keep last best data available in the viewer
- **be kind**: 
    - must not overwhelm (Denial of Service) any data sources
    - if a ton of API calls or HTTP requests need to be made, then orchestrate and rate-limit those requests
- allow for aggregation of multiple data sources for display
  - example: combine NWS flood gauges with USGS streamflow gauges for display on the map
    - deduplicate any gauges that exist in both sources with preference to NWS data
  - aggregation exists outside of the ETL processes for the source data
- able to trigger external events at any step (when data is ready)
  - example: trigger SMS notification service for gauge subscriptions when a gauge is predicted to flood
  - example: push-to-cartodb service that sync's ready-for-display output with CartoDB tables
  - these external services should only be loosely coupled to the pipeline
  - exact trigger mechanism to be determined, but an example would be via HTTP callback or message queue

## data service needs
- service just needs to have a simple API to support charts and graphs on front-end
  - most likely a small wrapper around the datastore
  - output as JSON
  - queries will answer questions like
    - "give me all the data at gauge <X> from '2016-03-17' to now"
    - "give me all the streamflow gauges within bbox"
      - this can be done with simple ranges and an x and y for gauges, does not need to be a full-blown geospatial engine
      - more complete geospatial queries like distance would be nice to have, but not critical
- **fault-tolerant**: the data service is critical
- **scalable**
  - for sake of planning, assume we will need to be able to handle ~10000 users at peak
  - peaks will be during flood events, with low traffic in between

## considerations
- **realtime is important**
  - data provided need to be as timely as possible
  - we'll need to resort to polling for initial pipeline Extract step for but the following steps should be able to trigger each other via notifications, events or message queue
- most data will timeseries data, so timeseries should be well supported
  - need to be able to handle timeseries queries
  - use good practices for timeseries data
    - store all timestamps as UTC, convert to UTC at the very beginning of pipeline
    - will be converted to local timezones at last possible step, for presentation to users (so intermediate steps don't need to worry about it)
    - if there is no native datetime type, use [ISO 8601 strings](https://en.wikipedia.org/wiki/ISO_8601)
- we don't have an ops team to keep things afloat, so we need to lean heavily on managed services
- we have access to virtually any of the AWS services
- additional third-party services are possible but procurement is tricky and will take 3-4 weeks

**Comment by sashahart** [comment]
I'm looking for clarification on consumers for the purpose of thinking about how this will be designed. Please correct the below as needed - here I'm saying things for the purpose of having them checked.

I gather that the frontend will directly use weather radar #39 and rain forecast #40 so that these are not involved in the pipeline at least in MVP; maybe NOAA/NWS data could end up in the pipeline eventually, but see next paragraph about that.

I gather that the frontend will prefer to consume map layers (e.g. flood gauges, reservoirs, maybe road crossings) from CartoDB per #46. (This also relies on certain assumptions, e.g. about finding an alternative or fix for the limitations of sync). So from the point of view of the pipeline, CartoDB is just a destination to export to.

With regard to "data service" I would guess that you also want to drive frontend charts (via some little API written e.g. in Node) from DynamoDB using time as a range key, and you probably want to keep large amounts of historical data in it. I guess that because it seems like a reasonable use to me. 

I'm less sure of what we want for the notification system because I'm less sure of how it will use data.
I suppose we can look for gauges that have some subscribers, and are in a floody condition now. Doing this in DynamoDB may be a little complex or slow. Once we have some candidate gauges, we have a choice of how to proceed. We can use history to determine whether their floody condition just increased, which also allows us to detect flapping. I imagine DynamoDB can do this part efficiently. If we don't use history, our alternative is to see if we previously notified them of an equally or more floody condition within some predefined time window, and I don't really see any advantage in that. So, maybe we want multiple datastores for notifications, and the history one can be DynamoDB.

For internal data processing jobs like integrating flood gauge data across systems, I think DynamoDB will be awkward to use for things like joins, requiring contortions like map-reduce. 

I think it might be useful to add PostgreSQL (on RDS for purposes of reducing ops/procurement headaches) for internal-only, general purpose use and to feed the notification system and probably also to feed CartoDB. We can leave DynamoDB for the time series stuff you need to read scalably and store approximately forever, whereas PostgreSQL can include more kinds of data and be cleaned up more aggressively, and also not suffer from significant extra load during heavy traffic.

Thoughts? Corrections?

**Comment by wilsaj** [comment]
> I gather that the frontend will directly use weather radar #39 and rain forecast #40 so that these are not involved in the pipeline at least in MVP; maybe NOAA/NWS data could end up in the pipeline eventually, but see next paragraph about that.

Yep. I don't foresee Weather Radar ever being part of the pipeline since near-realtime animated weather is pretty involved and and Aeris solves that problem well. Forecast is something that we might look into, but not high priority.

> I gather that the frontend will prefer to consume map layers (e.g. flood gauges, reservoirs, maybe road crossings) from CartoDB per #46. (This also relies on certain assumptions, e.g. about finding an alternative or fix for the limitations of sync). So from the point of view of the pipeline, CartoDB is just a destination to export to.

In my mind, I add one level of indirection. I consider the Push-to-CartoDB service it's own separate thing, and *that* is what the pipeline exports to.

> With regard to "data service" I would guess that you also want to drive frontend charts (via some little API written e.g. in Node) from DynamoDB using time as a range key, and you probably want to keep large amounts of historical data in it. I guess that because it seems like a reasonable use to me.

Yes, data service is just an API for getting data for the gauge charts. Not even necessarily large amounts of historical data. The app is just worried about current flood and developing conditions so history of about 2 weeks prior and any predictions/forecast with a window of about 1-5 days is all we really need. I think even range queries aren't going to be necessary, to be honest. It isn't unreasonable to include more data, but we can also just shove all we need into a single DynamoDB document to keep it real simple for the front-end & API.

> I'm less sure of what we want for the notification system because I'm less sure of how it will use data.
I suppose we can look for gauges that have some subscribers, and are in a floody condition now. Doing this in DynamoDB may be a little complex or slow. Once we have some candidate gauges, we have a choice of how to proceed. We can use history to determine whether their floody condition just increased, which also allows us to detect flapping. I imagine DynamoDB can do this part efficiently. If we don't use history, our alternative is to see if we previously notified them of an equally or more floody condition within some predefined time window, and I don't really see any advantage in that. So, maybe we want multiple datastores for notifications, and the history one can be DynamoDB.

I consider the SMS system its own separate thing, too - it very well may have a separate datastore. Managing subscriptions isn't the responsibility of this pipeline, the pipeline only needs to send messages to the SMS system that say things like: "Gauge ABC is now in moderate flood as of 11:20PM", "Gauge ABC is predicted to go into major flood at 1:43AM". It will be the responsibility of the SMS system to keep track of who (if anyone) has subscribed to Gauge ABC, send messages to all of those people, deal with errors in delivery, etc. It will also need to deal with things like flapping and making decisions about how much a situation needs to have changed before sending a new notification out.


> For internal data processing jobs like integrating flood gauge data across systems, I think DynamoDB will be awkward to use for things like joins, requiring contortions like map-reduce.

I agree that trying to replicate relations and joins via DynamoDB is not a good approach. I picture this sort of data processing happening completely outside the datastore, either in their own scripts or via AWS lambda functions. For the gauge aggregation example: The sets of gauges are small enough that they will fit comfortably in memory, so the process there would be to fetch both complete sets of gauges and then do the filtering in program logic, and then the merged gauges would be sent further down the pipeline.


> I think it might be useful to add PostgreSQL (on RDS for purposes of reducing ops/procurement headaches) for internal-only, general purpose use and to feed the notification system and probably also to feed CartoDB. We can leave DynamoDB for the time series stuff you need to read scalably and store approximately forever, whereas PostgreSQL can include more kinds of data and be cleaned up more aggressively, and also not suffer from significant extra load during heavy traffic.

RDS reduces headaches for sure, but is still non-trivial to admin and maintain. There are a few other pro and cons, but the lower operational burden is the main reason I want to make an effort to explore whether DynamoDB acting as a simple document store is going to be good enough.

**Comment by sashahart** [comment]
I think this issue will be a valuable reference for these high-level ideas. But if it's okay with you, I would like to close out this broad, high-level discussion in favor of smaller-scale discussions focused on what needs to be delivered at interfaces. If there is anything outstanding here, can we generate separate issues and then close this?
