### ISSUE TITLE
USGS NWIS streamflow gauges

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#42]
Streamflow data from the USGS National Water Information System
## source
- Huge network of gauges run by USGS
- Is a super-set of the NWS AHPS gauges (#37) but USGS source does not contain info about flood stage or predictions, only observed values
- Well documented at: http://waterservices.usgs.gov/rest/IV-Service.html
- Ulmo can be used to download & parse the data: https://github.com/ulmo-dev/ulmo
## status
- [ ] waiting on #36 to determine how to implement

**Comment by sashahart** [comment]
Due to the existence of ulmo and great docs, I'd guess <10hrs to do the data fetching and cleanup and not much more to dump into a table somewhere (I do think different data sources should import to different tables in the pipeline-internal database). And any slightly competent person can do it.

I'm less certain about the extra time needed to achieve integration with NWS AHPS gauge data and propagation of combined data out to all consuming subsystems, and to ensure update frequency. But it should be more predictable after we have done it with NWS AHPS since the structure of the data we are using will be similar.
