### ISSUE TITLE
Push to CartoDB service

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#46]
A service that pushes updates to CartoDB when new data is available.

## needs
- data sources will be periodically scraped and processed via data pipeline (see: #36)
- when updates are ready, this service will
  - determine what updates need to be made
  - batch them and update tables on CartoDB via the SQL API
- see this blog post: http://blog.cartodb.com/election-maps-with-the-power-and-beauty-of-cartodb for the general approach
- we are currently using CartoDB's sync feature for the prototype, but it has some limitations:
  - sync can be triggered, at best, every 15 minutes
  - does not fail gracefully
    - does not have any error handling or logs, so not possible to determine why it failed
    - cannot notify us when it fails
    - the dataset table ends up blank when this happens, meaning the map layer will be blank
    - usually requires a "hard reset" by either generating a duplicate version of the dataset/visualization or contacting by CartoDB support

## status
- [x] design
- [x] implementation
- [x] deployment

**Comment by sashahart** [comment]
I take it that the SQL API is a lower-level API that we can use (along with some other glue) to replace sync, is that correct?

**Comment by wilsaj** [comment]
Yep, that's right. CartoDB's sync feature just takes a source file and uses it to replace a table wholesale. The SQL API can update the table in place via INSERT, DELETE and UPDATEs.

**Comment by sarasafavi** [comment]
Progress: we have a Celery task which uses the SQL API to push updates to a table on CartoDB. For testing purposes, I scheduled this to run every minute to push a timestamp into a table on my account and it seemed to work fine.

One major caveat is that CartoDB does some caching. Browser clients in particular will probably want to send `Cache-Control: no-cache` to avoid getting a 304, or a 200 delivered out of some cache (CartoDB's Varnish?). Since CartoDB's dashboard doesn't do this, views of the dataset or related maps from within the CartoDB UI will probably be out-of-date (I was seeing ~10 minute delays just in casual testing).

Here's the commit where the test task went in, just for fun: https://github.com/TNRIS/flood-pipeline/commit/ff1f45eee2f4cbf1c49cbf84d5dad0a563009500

**Comment by sashahart** [comment]
This is more or less feature complete since Thursday. I say that because I've been running it for a few days on my machine and it has worked pretty reliably so far, NWS fetch/parse to CartoDB push.

This really leaves two major issues

1. To ensure the frontend is getting exactly what it needs from that CartoDB table. Although I've tried to guess, I really don't know exactly what the frontend will want in what form, so I am pretty sure this will need some work. I can't know what to do unless I have feedback or some kind of spec.

2. Final deployment issues. But this should be relatively easy due to the simplicity of the deploy model we have up front (the EC2 box running docker-compose, plus an RDS instance)

To give more detail on what's happening:

- pipeline is downloading an 'index' document containing current lids at a regular interval (it's trivial whether we use get_map_points.json scrape or the REST API, same results either way and actually I'm collecting both for purposes of comparison, but only one is needed to drive polling)

- Completion of that job is driving many per-lid requests for NWS AHPS hydrograph XML documents, which are saved to local filesystem in raw form in case something needs to be debugged. These requests are retried with a backoff policy in the event of simple request errors. There is a global request rate limit of 1/s. A timeout is enforced for each download of about 10s.

- Completion of each of those tasks is driving a parse job, which parses XML and create records in an internal database. (Currently and ideally this is a little spaced out to help ensure that queues drain, so there is typically a pause between the end of one polling pass and the start of another.) If there is no data for a given gauge or it's out of service, we just wait until next polling pass to hear more about it. Here I am skipping some hairy details about how we merge all the timeseries to avoid duplication

- There is an end_poll task kicked off when all those download and parse tasks are done, but currently all it does is drive retries of downloads for malformed docs (essentially, at the end of each polling pass over the lids, it generates a secondary polling pass just for failed lids)

- Separately from this, every minute there is a CartoDB push job which queries the internal database for the latest on each gauge and pushes one big upsert using CartoDB SQL API. 

- If a worker process goes down, docker-compose tries to restart it.

- When pipeline starts (and hence when it restarts) it purges its task queues - since it will just start a new polling pass soon anyway - then pauses a little bit to avoid hammering anything too hard in the event of flapping - then it kicks off the first polling pass as described above. 

- If you drop the internal table it just populates it in the next polling pass. The growth of data in the database is such that it should take roughly 3 gigs per 2 weeks of data, which is as long as we could reasonably want because that is how far back we get from the hydrograph XML docs. Currently there is no automated deletion of the old rows but it should be pretty easy to do and in a pinch a cron job could just delete all the observations every day

**Comment by sashahart** [comment]
This is working
