### ISSUE TITLE
add analytics to track how the site is being used

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#77]

**Comment by sashahart** [comment]
If we are not done adding analytics, we should probably get some specification of what kinds of tracking we need to add specifically for "mvp". If we are done or have no specific requirements, issues can be opened for further requirements as they are decided.

**Comment by wilsaj** [comment]
There should be analytics events for actions to get a sense for how users are interacting with the app. Things like:
- turning on and off layers
- opening and closing popups
- (maybe) pan/zoom to get a sense of which geographic areas users are interested in

**Comment by sashahart** [comment]
Maybe there should be. I don't know. But I have a point of process here, which is part of trying to manage a transition away from "one-developer project" and just clean up the backlog because it shouldn't be your job and nobody else is going do it.

Ideally, I want feature requests to come from specific people inside TNRIS who decided to advocate for that request, not just be an impersonal "there should be" which is really generated by a developer. Then we get a lot of stuff on the backlog nobody asked for.

Ideally, I want feature requests to be requirements from stakeholders, not nebulous "shoulds" which aren't part of acceptance criteria. Otherwise the backlog piles up with stuff that isn't really meant to be acted on, or not necessarily meant to be acted on. 

Ideally, I want each request to be defined, at least as far as the stakeholder can define it, but no open-ended "things like." Then we get a backlog piled up with issues that can't close and can absorb any amount of development time because there is no scope.
