### ISSUE TITLE
remove scroll bar on drawer

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#88]
From MP:

> There is a scroll bar between the data layers panel and the map panel, before we were able to just scroll without the bar (it  is visible below, using firefox on a windows environment).

![image](https://cloud.githubusercontent.com/assets/303866/15509556/8444c5b0-2199-11e6-87f1-ba08b7ae6650.png)

**Comment by sashahart** [comment]
After poking around at this with Firefox, Chrome and MS Edge on Windows and then with Firefox on Linux (all against the presently deployed site): I'm pretty sure the scroll bar is showing because the browser window is too short to include the "MORE RESOURCES" section. 

We have a few options. 

0. Leave this as-is. Users can ignore it, or resize vertically.

1. Reduce the vertical size of content (e.g. by removing "more resources") in the left-side div.nav so that the scrollbar is less likely to appear under normal usage.

2. Suppress the scrollbar forcibly, e.g. by setting overflow:hidden. This leaves the user with no cue that there is additional content in the left-side div.nav, so that they would have to guess there might be more to see, then resize the window or focus the div and scroll.

**Comment by wilsaj** [comment]
Setting `overflow:hidden` (option 3) makes it impossible to scroll in a lot of common contexts (for example, I can't use the trackpad on my laptop).

**Comment by wilsaj** [comment]
I think what happened is that before the legend info was added, the content was small enough that it wasn't noticed in most cases. Now there is enough content, that scrolling is necessary.

Probably pulling some content out is the right way to do it, but it is a bit tricky because where does that content go? How do people know how to get to it? Seems like a lot of work for marginal aesthetic gain.

**Comment by sashahart** [comment]
Agreed. I personally favor option 1, which doesn't require any code changes. As much as I like to close tickets which seem to be in limbo, I don't want to autocratically close tickets because of my personal opinions. So my goal with the PR was to try to spur the process forward a bit, one way or the other. I didn't anticipate takers for option 2, but in any case it would require further specification from someone who is not me. So I offered a PR for option 3 speculatively to try to move the issue forward and I'm ultimately indifferent as to whether it is merged or not, as long as the end state is what TNRIS wants and I get to close the ticket in good conscience :)

**Comment by wilsaj** [comment]
Yeah, I totally understand and appreciate your efforts - I'm just weighing in where I can.

I guess this is up to Richard and Miguel to decide whether or not option 1 is okay, given the limitations.

**Comment by sashahart** [comment]
Unless someone comes in I'm going to suggest the closure of this and the associated PR in a week or so. I'm not down with this zombie issue stuff, and it can be re-raised if it becomes interesting to someone again.

**Comment by sashahart** [comment]
no interest has been expressed, closing
